#!/bin/sh

daemonpath="/usr/local/bin"
daemonname="iScroll2Daemon"
daemonpidfile="/var/run/${daemonname}.pid"

. /etc/rc.common

StartService ()
{
    ConsoleMessage "Starting iScroll2"
    "${daemonpath}/${daemonname}"
}

StopService ()
{
    ConsoleMessage "Stopping iScroll2"
    kill $(cat "${daemonpidfile}")
}

RestartService () { StopService; StartService; }

RunService "$1"
