#!/bin/sh

daemonpath="/Library/StartupItems/iScroll2"
daemonname="iScroll2Daemon"
daemonpidfile="/var/run/${daemonname}.pid"

. /etc/rc.common

StartService ()
{
    ConsoleMessage "Starting iScroll2"
    "${daemonpath}/${daemonname}"
    ConsoleMessage -S
}

StopService ()
{
    ConsoleMessage "Stopping iScroll2"
    kill $(cat "${daemonpidfile}")
    ConsoleMessage -S
}

RestartService () { StopService; StartService; }

RunService "$1"
