#!/bin/sh

echo "Checking if Apple trackpad driver is loaded..."
if ! kextstat | grep com.apple.driver.AppleADBMouse > /dev/null
then 
    echo "ERROR: Apple trackpad driver not loaded!"
    exit $[(3<<5)+16]
fi
echo "Apple trackpad driver is loaded."
echo "Checking if trackpad supports W-Enhanced mode..."
if ! ioreg -n AppleADBMouseType4 | grep "W Enhanced Trackpad" > /dev/null
then
    echo "ERROR: Trackpad does not seem to support W-Enhanced mode."
    exit $[(3<<5)+17]
fi
echo "Trackpad seems to support W-Enhanced mode."
exit 0
