#!/bin/sh
# preflight
pref=/Library/PreferencePanes/iScroll2.prefPane
kext=System/Library/Extensions/iScroll2.kext

if [ -e "$pref" ]; then
    rm -rf "$pref"
fi

if [ -e "$kext" ]; then
    rm -rf "$kext"
fi

exit 0
